services:
  - type: web
    name: receiver
    env: php
    repo: https://github.com/ArapKBett/Rcr  # Optional, if using GitHub
    buildCommand: composer install
    startCommand: php -S 0.0.0.0:$PORT
    envVars:
      - key: PHP_VERSION
        value: 8.1
